FROM node:20-alpine3.19

ENV APP_ROOT /app

WORKDIR ${APP_ROOT}

RUN apk add --update --virtual .build-deps --no-cache \
      python3 \
      make \
      g++ \
    && rm -rf /var/cache/apk/*

COPY ["package.json", "package-lock.json*", "./"]

RUN npm ci  \
    && apk del .build-deps

ADD . ${APP_ROOT}

RUN npm install

EXPOSE ${PORT}

CMD ["npm", "run", "start:dev"]